
---
- name: java7 version selected
  alternatives: name=java path=/usr/lib/jvm/java-7-oracle/jre/bin/java

- name: javac7 version selected
  alternatives: name=javac path=/usr/lib/jvm/java-7-oracle/bin/javac

- name: M2_HOME
  lineinfile: dest=/home/tge/.bashrc regexp='^export M2_HOME' line='export M2_HOME=/opt/maven/apache-maven-3.2.5'

- name: JAVA_HOME
  lineinfile: dest=/home/tge/.bashrc regexp='^export JAVA_HOME' line='export JAVA_HOME=/usr/lib/jvm/java-7-oracle'
